// Types
export type { ColorVariant, CornerStyle } from "./types";

// Components
export * from "./components/Layout";
export * from "./components/Text";
export * from "./components/Surface";
export * from "./components/Badge";
export * from "./components/SlotFillBar";
export * from "./components/Legend";
export * from "./components/StatusLight";
export * from "./components/Dot";
export * from "./components/TruthIndicator";
export * from "./components/QuickFilter";
export * from "./components/MultiSelectFilter";
export * from "./components/HeartbeatSparkline";
export * from "./components/LiveHeartbeatTrace";
export * from "./components/ConnectionStatus";
export * from "./components/ConversationTree";
export * from "./components/MessageBubble";
export * from "./components/ParticipantAvatar";
export * from "./components/ParticipantNameLabel";
export * from "./components/ParticipantTimeLabel";
export * from "./components/ThreadGroup";
export * from "./components/LabeledDivider";
export * from "./components/Chart";
export * from "./components/Alarm";
export * from "./components/GroupBracket";
export * from "./components/RecentStarred";
export * from "./components/Cell";
export * from "./components/Button";
export * from "./components/Card";
export * from "./components/DataDisplay";
export * from "./components/Feedback";
export * from "./components/Icon";
export * from "./components/Inputs";
export * from "./components/Navigation";
export * from "./components/OverflowNav";
export * from "./components/Toggle";
export * from "./components/Progress";
export * from "./components/ProgressCard";
export * from "./components/Heatmap";
export * from "./components/Treemap";
export * from "./components/HeatStack";
export * from "./components/HeatStream";
export * from "./components/HeatStreamGrid";
export * from "./components/Table";
export * from "./components/PivotGrid";
export * from "./components/Section";
export * from "./components/Panel";
export * from "./components/Divider";
export * from "./components/Page";
export * from "./components/Modal";
export * from "./components/Tabs";
export * from "./components/TabbedSidePanel";
export * from "./components/ButtonGroup";
export * from "./components/List";
export * from "./components/PopoverMenu";
export * from "./components/Selector";
export * from "./components/TitledTimeRangeHeader";
export * from "./components/DataList";
export * from "./components/MathFormula";
export * from "./components/ProgressCheck";
export * from "./components/BurndownChart";
export * from "./components/SprintSelector";
export * from "./components/DagChart";
export * from "./components/SwimlaneChart";
export * from "./components/AnimatedSwimlaneChart";
export * from "./components/DragDrop";
export * from "./components/Duration";
export * from "./components/Dropdown";
export * from "./components/TagInput";
export * from "./components/ResizableContainer";
export * from "./components/Tooltip";
export * from "./components/Select";
export * from "./components/Combobox";
export * from "./components/ThemedNumberInput";
export * from "./components/Toast";
export * from "./components/ValueRenderer";
export * from "./components/DiffPair";
export * from "./components/ChangeRenderer";
export * from "./components/CandlestickRenderer";
export * from "./components/DateRangePicker";
export * from "./components/ThreePanelLayout";
export * from "./components/Markdown";
export * from "./components/Kbd";
export * from "./components/CollapsiblePanel";
export * from "./components/WeekCalendar";
export * from "./components/ActionRow";
export * from "./components/AssigneeChips";

// Styles - import this in your app: import "solid-ui-components/styles.css"

// Backward compatibility — will be removed in a future version
export { Page as HUDPage } from "./components/Page";
export { Section as HUDSection } from "./components/Section/Section";
export { Panel as HUDPanel } from "./components/Panel/Panel";
export { Modal as HUDModal } from "./components/Modal";
export { ConfirmationModal as HUDConfirmationModal } from "./components/Modal";
export { Tabs as HUDTabs } from "./components/Tabs";
export { ButtonGroup as HUDButtonGroup } from "./components/ButtonGroup";
export { List as HUDList, ListItem as HUDListItem } from "./components/List";
export { createPanel as createHUDPanel } from "./components/Panel";
export * from "./components/WorkerCard";
export * from "./components/CompletionTimeline";
export * from "./components/ThroughputChart";
export * from "./components/RingChart";
// export * from "./components/PivotTreemap"; // local-link build workaround: dir not committed
export * from "./components/AreaFocusGrid";
export * from "./components/ProductGridCard";
export * from "./components/FocusLabelBand";
export * from "./components/ProductGrid";

// Hooks
export * from "./hooks";
